version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: seu_usuario_pg
      POSTGRES_PASSWORD: sua_senha_pg
      POSTGRES_DB: ia_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: